name: Example App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Tuist Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tuist/tuist-action@0.13.0
        with:
          command: 'dependencies'
          arguments: 'fetch -p ExampleApp'
      - uses: tuist/tuist-action@0.13.0
        with:
          command: 'build'
          arguments: '-p ExampleApp'
